name: ci

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/ci.yml"
      - "build.gradle.kts"

permissions:
  packages: write

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: jdk17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: checkout
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build -Dquarkus.package.type=uber-jar

      - name: Make and push container image
        if: github.ref == 'refs/heads/main'
        run: ./gradlew quarkusBuild -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
